from pydantic import BaseModel, Field, EmailStr
from typing import List, Dict, Any, Optional

class Candidate(BaseModel):
    """
    Candidate model defining the core profile details of an applicant.
    """
    id: Optional[str] = Field(default=None, description="Unique identifier for the candidate, typically MongoDB ObjectId.")
    name: str = Field(..., description="Full name of the candidate.")
    email: EmailStr = Field(..., description="Contact email address.")
    phone: Optional[str] = Field(default=None, description="Contact phone number.")
    github_url: Optional[str] = Field(default=None, description="Link to candidate's GitHub profile.")
    portfolio_url: Optional[str] = Field(default=None, description="Link to candidate's personal portfolio or website.")
    linkedin_url: Optional[str] = Field(default=None, description="Link to candidate's LinkedIn profile.")
    extra_urls: List[str] = Field(default_factory=list, description="Other relevant URLs found in the resume (e.g. certificates, hackathons, coding platforms).")
    resume_text: str = Field(..., description="Raw text parsed from the candidate's resume.")
    skills: List[str] = Field(default_factory=list, description="List of skills extracted from the resume.")
    experience_years: float = Field(default=0.0, description="Total years of professional experience.")
    work_history: List[Dict[str, Any]] = Field(default_factory=list, description="Employment details (company, role, timeline).")
    education: List[Dict[str, Any]] = Field(default_factory=list, description="Education details (degree, major, school, year).")
    evaluations: Optional[Dict[str, Any]] = Field(default=None, description="Detailed AI evaluations attached to this candidate.")


class Job(BaseModel):
    """
    Job model representing the hiring requirements and description.
    """
    id: Optional[str] = Field(default=None, description="Unique identifier for the job posting.")
    title: str = Field(..., description="Job title.")
    job_description: str = Field(..., description="Raw text of the job description.")
    required_skills: List[str] = Field(..., description="List of mandatory technical and soft skills.")
    preferred_skills: List[str] = Field(default_factory=list, description="List of nice-to-have skills.")
    experience_required_years: float = Field(..., description="Minimum years of experience required.")
    ranking: Optional["Ranking"] = Field(default=None, description="The final consensus ranking tier and decision.")


class Evidence(BaseModel):
    """
    Evidence model representing verified files, portfolios, or external records
    gathered by the system during verification tasks.
    """
    id: Optional[str] = Field(default=None, description="Unique identifier for this evidence record.")
    evidence_type: str = Field(..., description="Type of evidence: e.g., 'GitHub', 'DriveFile', 'WebsiteContent', 'YouTubeVideo', 'PDF', 'OCRText', 'Certificate'.")
    source_url: str = Field(..., description="Source URL or path where evidence was collected.")
    verification_status: str = Field(..., description="Verification status: e.g., 'verified_active', 'broken_link', 'failed_ocr', 'unverified'.")
    content_summary: str = Field(..., description="Brief summary of what was found or parsed from this source.")
    extracted_metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata captured (e.g., certificate issue date, github stars, video length).")


class TechnicalEvaluation(BaseModel):
    """
    Evaluation model generated by the Technical Evaluator node.
    Focuses on hard technical capabilities, depth, open source contributions, and coding performance.
    """
    skills: List[str] = Field(..., description="Verified technical skills.")
    projects: List[Dict[str, Any]] = Field(..., description="Key projects verified, along with technical complexity rating.")
    technical_depth: str = Field(..., description="Detailed textual assessment of candidate's engineering depth.")
    github: Dict[str, Any] = Field(..., description="Assessment of repository activity, code quality, and star count.")
    coding_profiles: List[Dict[str, Any]] = Field(..., description="Analysis of coding platform profiles (LeetCode, HackerRank, Codeforces).")
    research: List[str] = Field(..., description="Academic publications, research papers, or patents.")
    open_source: List[str] = Field(..., description="Analysis of contributions to public/open-source projects.")
    technical_strengths: List[str] = Field(..., description="Top 3-5 technical strengths identified.")


class VerificationEvaluation(BaseModel):
    """
    Evaluation model generated by the Verification Evaluator node.
    Acts as an auditor checking timeline consistency, authenticity, and broken links.
    """
    evidence_audited: List[Dict[str, Any]] = Field(..., description="Detailed audit status of each evidence item.")
    portfolio_authenticity: str = Field(..., description="Assessment of personal portfolio quality and authenticity.")
    certificates_verified: List[Dict[str, Any]] = Field(..., description="List of certificates validated against issuing authorities or records.")
    github_authenticity: str = Field(..., description="Audit of GitHub activity to detect bot patterns, purchased accounts, or simple forks.")
    timeline_consistency: str = Field(..., description="Detailed analysis of employment/education timeline consistency, flag overlaps or unexplained gaps.")
    broken_links: List[str] = Field(..., description="List of non-functional URLs from the profile/resume.")
    confidence_score: float = Field(..., description="A float score (0.0 to 1.0) representing the overall audit confidence.")


class SkillMatch(BaseModel):
    """
    Sub-model for strict validation of skill matches.
    """
    skill: str = Field(..., description="The name of the skill.")
    matched: bool = Field(..., description="True if the candidate possesses this skill, False otherwise.")
    evidence: str = Field(default="", description="Evidence or context for this match.")


class JobMatchEvaluation(BaseModel):
    """
    Evaluation model generated by the Job Matching Evaluator node.
    Acts like a hiring manager, mapping candidate strengths against the job description.
    """
    job_id: str = Field(..., description="Reference ID of the job description.")
    required_skills_match: List[SkillMatch] = Field(..., description="Mapping of required skills indicating match status and evidence.")
    preferred_skills_match: List[SkillMatch] = Field(..., description="Mapping of preferred skills indicating match status and evidence.")
    experience_match: str = Field(..., description="Narrative analysis comparing candidate's experience level with the job's minimum requirement.")
    industry_match: str = Field(..., description="Evaluation of domain/industry alignment (e.g. Fintech, Medtech, AI/ML).")
    skill_gap: List[str] = Field(..., description="List of critical required skills missing in the candidate's profile.")


class AgentAction(BaseModel):
    """
    Model for Recruiter Chatbot to decide whether to use a tool or reply to the user.
    """
    tool_name: Optional[str] = Field(default=None, description="The name of the tool to execute (e.g., 'EmailTool'). Leave null if answering conversationally.")
    tool_args: Optional[Dict[str, str]] = Field(default=None, description="Arguments to pass to the tool, such as 'to_email', 'subject', and 'body' for EmailTool.")
    reply: Optional[str] = Field(default=None, description="Conversational reply to the recruiter if no tool is used, or to provide context.")


class Ranking(BaseModel):
    """
    The final score and ranking generated by the Consensus Node.
    Constructed using deterministic Python code logic based on evaluation nodes.
    """
    final_score: float = Field(..., description="A deterministic score (0.0 to 100.0) combining tech, verification, and match scores.")
    rank_tier: str = Field(..., description="Assigned tier: e.g., 'Tier 1 - Strong Fit', 'Tier 2 - Good Fit', 'Tier 3 - Not Recommended'.")
    confidence: float = Field(..., description="Combined evaluation confidence score.")
    reason: str = Field(..., description="Detailed, step-by-step reason for this score calculation, making the decision transparent.")

class SupervisorDecision(BaseModel):
    """
    Model used by the LLM Supervisor to route the graph execution dynamically.
    """
    reasoning: str = Field(..., description="The logic and rationale behind choosing the next action.")
    next_action: str = Field(..., description="The exact name of the next node to trigger (e.g., 'parse', 'intelligence', 'tools', 'evaluate', 'consensus', 'report_generator', 'recruiter_chat', '__end__').")
