import re
import logging
from typing import Any, Dict
import httpx
from backend.tools.base import BaseTool

logger = logging.getLogger(__name__)

class GoogleDocsTool(BaseTool):
    """
    Tool to fetch and extract text content from public Google Docs.
    """
    name: str = "GoogleDocsTool"
    description: str = "Extracts plain text content from shared public Google Docs URLs."

    async def run(self, doc_url: str, *args: Any, **kwargs: Any) -> Dict[str, Any]:
        """
        Parses a public Google Doc URL, exports it to plain text, and returns the content.
        """
        logger.info(f"GoogleDocsTool fetching doc from URL: {doc_url}")
        try:
            # Match the document ID using regex: /document/d/DOC_ID/...
            doc_id_match = re.search(r"/document/d/([a-zA-Z0-9-_]+)", doc_url)
            if not doc_id_match:
                raise ValueError("Invalid Google Doc URL structure.")
                
            doc_id = doc_id_match.group(1)
            # Fetch the plain text exported version of the Doc
            export_url = f"https://docs.google.com/document/d/{doc_id}/export?format=txt"
            
            async with httpx.AsyncClient() as client:
                res = await client.get(export_url, timeout=10.0)
                res.raise_for_status()
                text = res.text
                
                return {
                    "doc_url": doc_url,
                    "doc_id": doc_id,
                    "extracted_text": text,
                    "text_length": len(text),
                    "success": True
                }
        except Exception as e:
            logger.error(f"GoogleDocsTool failed to load doc {doc_url}: {e}")
            return {
                "doc_url": doc_url,
                "error": str(e),
                "success": False
            }


class GoogleDocsWriterTool(BaseTool):
    """
    Tool to generate automated candidate evaluation reports via Google Docs API.
    """
    name: str = "GoogleDocsWriterTool"
    description: str = "Creates a new Google Doc and writes the evaluation report into it."

    async def run(self, candidate_name: str, score: float, tier: str, trust: float, *args: Any, **kwargs: Any) -> Dict[str, Any]:
        """
        Creates a new Google Doc, populates it, changes permissions to public read, and returns the URL.
        """
        import asyncio
        logger.info(f"GoogleDocsWriterTool generating report for {candidate_name}")
        
        try:
            from backend.tools.email import _build_google_services
            
            def _create_and_share_doc():
                services = _build_google_services()
                docs_service = services["docs"]
                drive_service = services["drive"]
                
                # 1. Create empty document
                doc = docs_service.documents().create(body={"title": f"Candidate AI Evaluation - {candidate_name}"}).execute()
                doc_id = doc.get("documentId")
                
                # 2. Insert text
                text = (
                    f"AI RECRUITMENT OS - CANDIDATE EVALUATION REPORT\n"
                    f"==============================================\n\n"
                    f"Candidate Name: {candidate_name}\n"
                    f"Final Consensus Score: {score}/100.0\n"
                    f"Rank Tier: {tier}\n"
                    f"Verification Trust: {trust}/100.0\n\n"
                    f"This report was automatically generated by the LangGraph Evaluation Pipeline."
                )
                
                requests = [
                    {
                        "insertText": {
                            "location": {"index": 1},
                            "text": text
                        }
                    }
                ]
                docs_service.documents().batchUpdate(documentId=doc_id, body={"requests": requests}).execute()
                
                # 3. Change permissions so anyone with link can view
                permission = {
                    "type": "anyone",
                    "role": "reader"
                }
                drive_service.permissions().create(fileId=doc_id, body=permission).execute()
                
                return f"https://docs.google.com/document/d/{doc_id}/view"
                
            report_url = await asyncio.to_thread(_create_and_share_doc)
            
            return {
                "success": True,
                "report_url": report_url
            }
        except Exception as e:
            logger.error(f"GoogleDocsWriterTool failed: {e}")
            return {
                "success": False,
                "error": str(e)
            }

